# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Zulun Zhu
# title: Your job title
email: ZULUN001@ntu.edu.sg
# phone: Your phone number (optional)
#website: Your website (eg. https://google.com)(optional)

# Social links
#twitter_username: jekyllrb
github_username:  ZulunZhu
#dribbble_username: jekyll
facebook_username: Zulun Zhu
#flickr_username: jekyll
instagram_username: poppingzoo
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
googleplus_username: Zulun Zhu

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: zulunzhu.JPG
about_content: | # this will include new lines to allow paragraphs
    Hi, my name’s Zulun Zhu and I graduated from **Zhejiang University** and **National University of Defense Technology** for bachelor and master stages respectively. Currently, I am a fourth-year Ph.D. candidate at **Nanyang Technological University**.
    During my PhD stage, I am focusing on the Database of Graphs, Machine Learning, Graph Neural Networks, and Spiking Neural Networks. For the master stage, simultaneous localization and
    mapping (SLAM) systems are mainly focused on. 
  


# Projects Section
projects_title: Publication #(Use this to override about projects section title)

# Experience Section
# experience_title: Research Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

 
      
# More Section
more_title: Awards and Hobbies #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
      ## Awards:
       - ĲCAI-24 Travel Grant, Outstanding Contribution Award of CVPR 2024 Embodied Al Workshop, PC member of KDD. 2024
       - 2nd Place of KDD Cup 2020 – Graph Adversarial Attacks & Defenses Track. 2020
       - National Scholarship, National Encouragement Scholarship. 2013 -2016
       - Zeng Xianzi Scholarship. 2013-2016

       
       ## Hobbies:
       - [Popping dance](https://www.bilibili.com/video/av5022452)
       - Photography
       - Playing guitar
       - Basketball （National second level referee）
       - Table Tennis
 
   

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
